version: '3.1'
services:
  web:
    image: melkawakibi/blogandportfolio
    ports:
      - 8080:80

  mysql:
    image: mysql:5.6
    ports:
     - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "root"