version: '3.1'
services:
  web:
    image: melkawakibi/blogandportfolio
    ports:
      - 8080:80

  mysql:
    image: mysql
    ports:
     - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    volumes:
     - mysqltest:/var/lib/mysql
volumes:
  mysqltest:
    driver: "local"